# Generated by Django 4.2.13 on 2024-07-12 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economia", "0003_delete_economiaeconomiaverificationcode_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthtokenToken",
        ),
        migrations.DeleteModel(
            name="CommentsLikes",
        ),
        migrations.DeleteModel(
            name="EconomiaVerificationcode",
        ),
        migrations.DeleteModel(
            name="Rules",
        ),
    ]
