# Generated by Django 4.2.13 on 2024-07-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economia", "0004_delete_authtokentoken_delete_commentslikes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthtokenToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField()),
                ("user_id", models.BigIntegerField(unique=True)),
            ],
            options={
                "db_table": "authtoken_token",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CommentsLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "comments_likes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EconomiaVerificationcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "economia_verificationcode",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communit_rule",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "personal_rule",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "youth_protection_rule",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "rules",
                "managed": False,
            },
        ),
    ]
