# Generated by Django 4.2.13 on 2024-07-19 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economia", "0005_authtokentoken_commentslikes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childcomments",
            options={"managed": True},
        ),
    ]
